# Úkol 10: Zaměstnanci a Projekty
***

## Zadání 1

Načti data o zaměstnancích z CSV souborů do tabulek (DataFrame). Ke každé tabulce přidej nový sloupec mesto, které bude obsahovat informaci o tom, ve kterém městě zaměstnanec pracuje.

In [126]:
import pandas
praha = pandas.read_csv("/Users/petrakrykorkova/Documents/Programování/zam_praha.csv")
praha["mesto"] = "Praha"
praha

          jmeno  prijimeni   telefonni_cislo  cislo_zamestnance  mesto
0         Brian       Hall  +421 949 656 098                 30  Praha
1         Marta   Kolářová       730 456 163                 32  Praha
2          John    Moravec       725 092 179                 33  Praha
3      Dominika    Kopecká       722 747 626                 34  Praha
4        Marcel      Hájek  +421 902 928 669                 35  Praha
5        Milada  Hernandez       773 373 704                 38  Praha
6     Catherine     Bender       604 068 460                 40  Praha
7          Olga    Němcová  +421 914 172 243                 41  Praha
8       Jeffrey    Šťastný       607 628 821                 44  Praha
9        Kamila     Říhová  +421 948 396 069                 47  Praha
10      Jaromír     Miller  +421 912 615 902                 49  Praha
11  Christopher      Zeman  +421 948 150 084                 51  Praha
12     Karolína      Short       721 589 083                 53  Praha
13     Michelle    Vlčková  +421 41 720 7806                 54  Praha
14      Jeffrey   Pospíšil  +421 55 491 6940                 56  Praha
15     Ladislav     Blažek  +421 910 274 975                 57  Praha
16         John     Bailey       775 021 116                 58  Praha
17      William    Shelton  +421 47 745 8219                 60  Praha
18    Miroslava     Veselá       774 029 254                 62  Praha
19      William  Alexander  +421 949 106 724                 63  Praha
20     Kimberly       Bass  +421 912 169 840                 64  Praha
21       Nathan    Svoboda       728 710 923                 66  Praha
22        Luděk     Bartoš  +421 940 700 326                 69  Praha
23       Dillon      Black       734 300 978                 70  Praha
24       Robert       Říha       727 351 984                 72  Praha
25        Steve      Šimek       604 966 101                 74  Praha
26      Theresa   Kučerová  +421 48 528 0081                 76  Praha
27        Marta     Butler  +421 944 196 827                 78  Praha
28     Samantha  Kadlecová  +421 904 841 543                 80  Praha

In [127]:
plzen = pandas.read_csv("/Users/petrakrykorkova/Documents/Programování/zam_plzeň.csv")
plzen["mesto"] = "Plzeň"
plzen

        jmeno    prijimeni   telefonni_cislo  cislo_zamestnance  mesto
0       Stacy  Pospíšilová       727 293 880                  3  Plzeň
1       Matěj         Král       770 787 377                  6  Plzeň
2      Amanda       Wilson  +421 52 656 7231                  7  Plzeň
3       Angel       Wilson  +421 52 135 2491                  8  Plzeň
4    Jindřich       Howell  +421 39 043 0948                 10  Plzeň
5   Alexander     Martinez       721 195 689                 13  Plzeň
6       Radim      Kopecký  +421 917 371 226                 16  Plzeň
7    Miroslav         Reed       774 829 074                 18  Plzeň
8      Emilie       Powell       731 380 539                 21  Plzeň
9      Nikola         Wade       726 763 154                 22  Plzeň
10  Katherine         Reed       726 214 968                 23  Plzeň
11      Kayla     Urbanová       737 772 985                 24  Plzeň
12      Roman       Moreno       722 284 985                 26  Plzeň
13   Bohumila        Smith       608 121 912                 27  Plzeň
14    Blažena        Smith  +421 51 828 2591                 28  Plzeň
15    Phillip         Malý       731 594 560                 29  Plzeň

In [128]:
liberec = pandas.read_csv("/Users/petrakrykorkova/Documents/Programování/zam_liberec.csv")
liberec["mesto"] = "Liberec"
liberec

        jmeno    prijimeni   telefonni_cislo  cislo_zamestnance    mesto
0        Nela      Šťastná       728 454 176                 83  Liberec
1     Heather      Marková       604 404 522                 84  Liberec
2      Krista  Procházková  +421 50 444 5544                 85  Liberec
3    Jennifer        Brown       775 545 190                 86  Liberec
4   Ladislava    Blackwell  +421 913 487 200                 87  Liberec
5      Robert       Macias  +421 49 929 6856                 88  Liberec
6        Dana        Reyes  +421 904 153 942                 90  Liberec
7       Vasyl       Veselý       603 759 413                 92  Liberec
8       Randy       Veselý       777 149 125                 95  Liberec
9      Audrey        Allen  +421 908 839 506                 96  Liberec
10       Ivan       Bartoš       603 226 051                 99  Liberec

Vytvoř novou tabulku zamestnanci a ulož do ní informace o všech zaměstnancích (operace concat).

In [131]:
zamestnanci = pandas.concat([praha, plzen, liberec])
zamestnanci = zamestnanci.reset_index(drop=True)
#zamestnanci.info()
zamestnanci

          jmeno    prijimeni   telefonni_cislo  cislo_zamestnance    mesto
0         Brian         Hall  +421 949 656 098                 30    Praha
1         Marta     Kolářová       730 456 163                 32    Praha
2          John      Moravec       725 092 179                 33    Praha
3      Dominika      Kopecká       722 747 626                 34    Praha
4        Marcel        Hájek  +421 902 928 669                 35    Praha
5        Milada    Hernandez       773 373 704                 38    Praha
6     Catherine       Bender       604 068 460                 40    Praha
7          Olga      Němcová  +421 914 172 243                 41    Praha
8       Jeffrey      Šťastný       607 628 821                 44    Praha
9        Kamila       Říhová  +421 948 396 069                 47    Praha
10      Jaromír       Miller  +421 912 615 902                 49    Praha
11  Christopher        Zeman  +421 948 150 084                 51    Praha
12     Karolína        Short       721 589 083                 53    Praha
13     Michelle      Vlčková  +421 41 720 7806                 54    Praha
14      Jeffrey     Pospíšil  +421 55 491 6940                 56    Praha
15     Ladislav       Blažek  +421 910 274 975                 57    Praha
16         John       Bailey       775 021 116                 58    Praha
17      William      Shelton  +421 47 745 8219                 60    Praha
18    Miroslava       Veselá       774 029 254                 62    Praha
19      William    Alexander  +421 949 106 724                 63    Praha
20     Kimberly         Bass  +421 912 169 840                 64    Praha
21       Nathan      Svoboda       728 710 923                 66    Praha
22        Luděk       Bartoš  +421 940 700 326                 69    Praha
23       Dillon        Black       734 300 978                 70    Praha
24       Robert         Říha       727 351 984                 72    Praha
25        Steve        Šimek       604 966 101                 74    Praha
26      Theresa     Kučerová  +421 48 528 0081                 76    Praha
27        Marta       Butler  +421 944 196 827                 78    Praha
28     Samantha    Kadlecová  +421 904 841 543                 80    Praha
29        Stacy  Pospíšilová       727 293 880                  3    Plzeň
30        Matěj         Král       770 787 377                  6    Plzeň
31       Amanda       Wilson  +421 52 656 7231                  7    Plzeň
32        Angel       Wilson  +421 52 135 2491                  8    Plzeň
33     Jindřich       Howell  +421 39 043 0948                 10    Plzeň
34    Alexander     Martinez       721 195 689                 13    Plzeň
35        Radim      Kopecký  +421 917 371 226                 16    Plzeň
36     Miroslav         Reed       774 829 074                 18    Plzeň
37       Emilie       Powell       731 380 539                 21    Plzeň
38       Nikola         Wade       726 763 154                 22    Plzeň
39    Katherine         Reed       726 214 968                 23    Plzeň
40        Kayla     Urbanová       737 772 985                 24    Plzeň
41        Roman       Moreno       722 284 985                 26    Plzeň
42     Bohumila        Smith       608 121 912                 27    Plzeň
43      Blažena        Smith  +421 51 828 2591                 28    Plzeň
44      Phillip         Malý       731 594 560                 29    Plzeň
45         Nela      Šťastná       728 454 176                 83  Liberec
46      Heather      Marková       604 404 522                 84  Liberec
47       Krista  Procházková  +421 50 444 5544                 85  Liberec
48     Jennifer        Brown       775 545 190                 86  Liberec
49    Ladislava    Blackwell  +421 913 487 200                 87  Liberec
50       Robert       Macias  +421 49 929 6856                 88  Liberec
51         Dana        Reyes  +421 904 153 942                 90  Liberec
52        Vasyl       Veselý       603 759 413                 92  Liberec
53        Randy       Veselý       777 149 125                 95  Liberec
54       Audrey        Allen  +421 908 839 506                 96  Liberec
55         Ivan       Bartoš       603 226 051                 99  Liberec

Ze souboru platy_2021_02.csv načti platy zaměstnanců za únor 2021. Propoj tabulku (operace join) s platy a tabulku se zaměstnanci pomocí sloupce cislo_zamestnance.

In [132]:
mzdy_unor = pandas.read_csv("/Users/petrakrykorkova/Documents/Programování/platy_2021_02.csv")
mzdy_unor

    cislo_zamestnance     plat
0                   3  54900.0
1                   6  54800.0
2                   7  36400.0
3                   8  47900.0
4                  16  34200.0
5                  18  35400.0
6                  21  54200.0
7                  22  34400.0
8                  23  39000.0
9                  24  44200.0
10                 26  59600.0
11                 27  45100.0
12                 28  38100.0
13                 29  48900.0
14                 30  33500.0
15                 32  53000.0
16                 33  38400.0
17                 34  36800.0
18                 38  32600.0
19                 40  32800.0
20                 41  49300.0
21                 44  52000.0
22                 47  40700.0
23                 49  58400.0
24                 51  37100.0
25                 56  39300.0
26                 57  36800.0
27                 63  31400.0
28                 64  36900.0
29                 69  32600.0
30                 70  52600.0
31                 74  49300.0
32                 76  55400.0
33                 78  52600.0
34                 80  57700.0
35                 83  46500.0
36                 84  38600.0
37                 85  44200.0
38                 87  49900.0
39                 90  41100.0
40                 92  48100.0
41                 95  31600.0
42                 96  50200.0

In [133]:
zamestnanci_mzdy = pandas.merge(zamestnanci, mzdy_unor, on="cislo_zamestnance", how="left")
zamestnanci_mzdy

,jmeno,prijimeni,telefonni_cislo,cislo_zamestnance,mesto,plat
0,Brian,Hall,+421 949 656 098,30,Praha,33500.0
1,Marta,Kolářová,730 456 163,32,Praha,53000.0
2,John,Moravec,725 092 179,33,Praha,38400.0
3,Dominika,Kopecká,722 747 626,34,Praha,36800.0
4,Marcel,Hájek,+421 902 928 669,35,Praha,NaN
5,Milada,Hernandez,773 373 704,38,Praha,32600.0
6,Catherine,Bender,604 068 460,40,Praha,32800.0
7,Olga,Němcová,+421 914 172 243,41,Praha,49300.0
8,Jeffrey,Šťastný,607 628 821,44,Praha,52000.0
9,Kamila,Říhová,+421 948 396 069,47,Praha,40700.0
10,Jaromír,Miller,+421 912 615 902,49,Praha,58400.0
11,Christopher,Zeman,+421 948 150 084,51,Praha,37100.0
12,Karolína,Short,721 589 083,53,Praha,NaN
13,Michelle,Vlčková,+421 41 720 7806,54,Praha,NaN
14,Jeffrey,Pospíšil,+421 55 491 6940,56,Praha,39300.0
15,Ladislav,Blažek,+421 910 274 975,57,Praha,36800.0
16,John,Bailey,775 021 116,58,Praha,NaN
17,William,Shelton,+421 47 745 8219,60,Praha,NaN
18,Miroslava,Veselá,774 029 254,62,Praha,NaN
19,William,Alexander,+421 949 106 724,63,Praha,31400.0
20,Kimberly,Bass,+421 912 169 840,64,Praha,36900.0
21,Nathan,Svoboda,728 710 923,66,Praha,NaN
22,Luděk,Bartoš,+421 940 700 326,69,Praha,32600.0
23,Dillon,Black,734 300 978,70,Praha,52600.0
24,Robert,Říha,727 351 984,72,Praha,NaN
25,Steve,Šimek,604 966 101,74,Praha,49300.0
26,Theresa,Kučerová,+421 48 528 0081,76,Praha,55400.0
27,Marta,Butler,+421 944 196 827,78,Praha,52600.0
28,Samantha,Kadlecová,+421 904 841 543,80,Praha,57700.0
29,Stacy,Pospíšilová,727 293 880,3,Plzeň,54900.0
30,Matěj,Král,770 787 377,6,Plzeň,54800.0
31,Amanda,Wilson,+421 52 656 7231,7,Plzeň,36400.0
32,Angel,Wilson,+421 52 135 2491,8,Plzeň,47900.0
33,Jindřich,Howell,+421 39 043 0948,10,Plzeň,NaN
34,Alexander,Martinez,721 195 689,13,Plzeň,NaN
35,Radim,Kopecký,+421 917 371 226,16,Plzeň,34200.0
36,Miroslav,Reed,774 829 074,18,Plzeň,35400.0
37,Emilie,Powell,731 380 539,21,Plzeň,54200.0
38,Nikola,Wade,726 763 154,22,Plzeň,34400.0
39,Katherine,Reed,726 214 968,23,Plzeň,39000.0
40,Kayla,Urbanová,737 772 985,24,Plzeň,44200.0
41,Roman,Moreno,722 284 985,26,Plzeň,59600.0
42,Bohumila,Smith,608 121 912,27,Plzeň,45100.0
43,Blažena,Smith,+421 51 828 2591,28,Plzeň,38100.0
44,Phillip,Malý,731 594 560,29,Plzeň,48900.0
45,Nela,Šťastná,728 454 176,83,Liberec,46500.0
46,Heather,Marková,604 404 522,84,Liberec,38600.0
47,Krista,Procházková,+421 50 444 5544,85,Liberec,44200.0
48,Jennifer,Brown,775 545 190,86,Liberec,NaN
49,Ladislava,Blackwell,+421 913 487 200,87,Liberec,49900.0
50,Robert,Macias,+421 49 929 6856,88,Liberec,NaN
51,Dana,Reyes,+421 904 153 942,90,Liberec,41100.0
52,Vasyl,Veselý,603 759 413,92,Liberec,48100.0
53,Randy,Veselý,777 149 125,95,Liberec,31600.0
54,Audrey,Allen,+421 908 839 506,96,Liberec,50200.0
55,Ivan,Bartoš,603 226 051,99,Liberec,NaN

Porovnej rozměry tabulek před spojením a po spojení. Pokud nemá některý zaměstnanec plat za únor, znamená to, že v naší firmě již nepracuje.

In [134]:
rozmer_z = zamestnanci.shape[0] == zamestnanci_mzdy.shape[0]
rozmer_z

True

In [135]:
rozmer_unor = mzdy_unor.shape[0]
rozmer_unor

43

Spočti průměrný plat zaměstnanců v jednotlivých kancelářích.

In [136]:
prumer_mesta = zamestnanci_mzdy.groupby("mesto")["plat"].mean()
prumer_mesta

mesto
Liberec    43775.000000
Plzeň      44792.857143
Praha      43295.238095
Name: plat, dtype: float64

## Zadání 2
Pokračuj ve své práci pro softwarovou firmu. Ze souboru vykazy.csv načti informace o výkazech na projekty pro jednoho vybraného zákazníka.

Načti data ze souboru a ulož je do tabulky.

In [137]:
zakaznik = pandas.read_csv("/Users/petrakrykorkova/Documents/Programování/vykazy.csv")
zakaznik

          date  hours project  emloyee_id
0   2021-02-01    2.5     F30          13
1   2021-02-01    3.4     W05          70
2   2021-02-01    2.1     JL9          72
3   2021-02-01    5.2     F30           3
4   2021-02-01    2.4     TE1          54
5   2021-02-01    4.1     TE1          83
6   2021-02-01    5.4     W05          92
7   2021-02-01    2.2     YLI          34
8   2021-02-01    2.7     YLI          84
9   2021-02-01    4.4     W05          30
10  2021-02-02    5.6     F30          53
11  2021-02-02    2.6     W05          47
12  2021-02-02    2.4     YLI          44
13  2021-02-02    3.1     YLI          40
14  2021-02-02    5.3     YLI          10
15  2021-02-02    3.6     YLI          53
16  2021-02-02    5.6     F30          56
17  2021-02-03    4.0     W05          53
18  2021-02-03    4.6     TE1          86
19  2021-02-03    2.6     F30          18
20  2021-02-03    2.8     TE1          47
21  2021-02-03    2.6     YLI          34
22  2021-02-03    3.7     YLI          96
23  2021-02-03    5.2     W05          57
24  2021-02-03    5.5     W05          40
25  2021-02-03    5.4     YLI          86
26  2021-02-03    2.1     TE1          87

Proveď agregaci a zjisti celkový počet vykázaných hodin za jednotlivé projekty.

In [138]:
zakaznik_ag = zakaznik.groupby("project")["hours"].sum()
zakaznik_ag

project
F30    21.5
JL9     2.1
TE1    16.0
W05    30.5
YLI    31.0
Name: hours, dtype: float64

## Nepovinný bonus 1

Ulož do proměnné počet zaměstnanců, kteří v naší firmě již nepracují.

In [139]:
pocet_odeslo = zamestnanci_mzdy["plat"].isna().sum()
pocet_odeslo

13

V rámci úspory se IT oddělení rozhodlo prověřit licence přidělené zaměstnancům, kteří ve firmě již nepracují. Vytvoř samostatnou tabulku, která obsahuje jména zaměstnanců, kteří ve firmě již nepracují. Tabulku ulož do souboru CSV.

In [182]:
jmena_odesli = zamestnanci_mzdy[zamestnanci_mzdy["plat"].isnull()].to_csv('jmena_odesli.csv')
jmena_odesli

## Nepovinný bonus 2

Propoj tabulku s výkazy s tabulkou se zaměstnanci, kterou jsi vytvořil(a) v předchozím cvičení.

Následně proveď statistiku vykázaných hodin za jednotlivé kanceláře, tj. spočítej celkový počet hodin vykázaný zaměstnanci jednotlivých kanceláří na projekty daného zákazníka.

In [156]:
data = pandas.merge(zakaznik, zamestnanci_mzdy, left_on="emloyee_id", right_on="cislo_zamestnance", how="left")
data

,date,hours,project,emloyee_id,jmeno,prijimeni,telefonni_cislo,cislo_zamestnance,mesto,plat
0,2021-02-01,2.5,F30,13,Alexander,Martinez,721 195 689,13,Plzeň,NaN
1,2021-02-01,3.4,W05,70,Dillon,Black,734 300 978,70,Praha,52600.0
2,2021-02-01,2.1,JL9,72,Robert,Říha,727 351 984,72,Praha,NaN
3,2021-02-01,5.2,F30,3,Stacy,Pospíšilová,727 293 880,3,Plzeň,54900.0
4,2021-02-01,2.4,TE1,54,Michelle,Vlčková,+421 41 720 7806,54,Praha,NaN
5,2021-02-01,4.1,TE1,83,Nela,Šťastná,728 454 176,83,Liberec,46500.0
6,2021-02-01,5.4,W05,92,Vasyl,Veselý,603 759 413,92,Liberec,48100.0
7,2021-02-01,2.2,YLI,34,Dominika,Kopecká,722 747 626,34,Praha,36800.0
8,2021-02-01,2.7,YLI,84,Heather,Marková,604 404 522,84,Liberec,38600.0
9,2021-02-01,4.4,W05,30,Brian,Hall,+421 949 656 098,30,Praha,33500.0
10,2021-02-02,5.6,F30,53,Karolína,Short,721 589 083,53,Praha,NaN
11,2021-02-02,2.6,W05,47,Kamila,Říhová,+421 948 396 069,47,Praha,40700.0
12,2021-02-02,2.4,YLI,44,Jeffrey,Šťastný,607 628 821,44,Praha,52000.0
13,2021-02-02,3.1,YLI,40,Catherine,Bender,604 068 460,40,Praha,32800.0
14,2021-02-02,5.3,YLI,10,Jindřich,Howell,+421 39 043 0948,10,Plzeň,NaN
15,2021-02-02,3.6,YLI,53,Karolína,Short,721 589 083,53,Praha,NaN
16,2021-02-02,5.6,F30,56,Jeffrey,Pospíšil,+421 55 491 6940,56,Praha,39300.0
17,2021-02-03,4.0,W05,53,Karolína,Short,721 589 083,53,Praha,NaN
18,2021-02-03,4.6,TE1,86,Jennifer,Brown,775 545 190,86,Liberec,NaN
19,2021-02-03,2.6,F30,18,Miroslav,Reed,774 829 074,18,Plzeň,35400.0
20,2021-02-03,2.8,TE1,47,Kamila,Říhová,+421 948 396 069,47,Praha,40700.0
21,2021-02-03,2.6,YLI,34,Dominika,Kopecká,722 747 626,34,Praha,36800.0
22,2021-02-03,3.7,YLI,96,Audrey,Allen,+421 908 839 506,96,Liberec,50200.0
23,2021-02-03,5.2,W05,57,Ladislav,Blažek,+421 910 274 975,57,Praha,36800.0
24,2021-02-03,5.5,W05,40,Catherine,Bender,604 068 460,40,Praha,32800.0
25,2021-02-03,5.4,YLI,86,Jennifer,Brown,775 545 190,86,Liberec,NaN
26,2021-02-03,2.1,TE1,87,Ladislava,Blackwell,+421 913 487 200,87,Liberec,49900.0

In [157]:
data_ag = data.groupby(["project","mesto"])["hours"].mean()
data_ag

project  mesto
F30      Plzeň      3.433333
         Praha      5.600000
JL9      Praha      2.100000
TE1      Liberec    3.600000
         Praha      2.600000
W05      Liberec    5.400000
         Praha      4.183333
YLI      Liberec    3.933333
         Plzeň      5.300000
         Praha      2.780000
Name: hours, dtype: float64